TITLE_AND_COMPOSER_TO_DATES = {
    ("Giulio Cesare in Egitto", "Georg Friedrich Händel"): {(None, 1724, None)},
    ("Thérèse Raquin", "Tobias Picker"): {(None, 2001, 2006)},
    ("Don Giovanni", "Wolfgang Amadeus Mozart"): {(None, 1787, None)},
    ("Don Carlo", "Giuseppe Verdi"): {(None, 1867, None)},
    ("La forza del destino", "Giuseppe Verdi"): {(None, 1862, None)},
    ("Theodora", "Georg Friedrich Händel"): {(None, 1750, None)},
    ("La Wally", "Alfredo Catalani"): {(None, 1892, None)},
    ("Deianira, Iole ed Ercole", "Nicola Antonio Porpora"): {(None, 1711, None)},
    ("Faust", "Charles Gounod"): {(None, 1859, None)},
    ("Proserpina", "Wolfgang Rihm"): {(None, 2009, None)},
    ("The Lighthouse", "Peter Maxwell Davies"): {(None, 1980, None)},
    ("Adriana Lecouvreur", "Francesco Cilèa"): {(None, 1902, None)},
    ("Der Waffenschmied", "Albert Lortzing"): {(None, 1846, None)},
    ("Peter Grimes", "Benjamin Britten"): {(None, 1945, None)},
    ("Zenobia, regina de’ Palmireni", "Tomaso Albinoni"): {(None, 1694, None)},
    ("Eugen Onegin", "Pjotr Iljitsch Tschaikowski"): {(None, 1879, None)},
    ("Iolanta", "Pjotr Iljitsch Tschaikowski"): {(None, 1892, None)},
    ("L’italiana in Londra", "Domenico Cimarosa"): {(None, 1778, None)},
    ("Il barbiere di Siviglia", "Gioachino Rossini"): {(None, 1816, None)},
    ("Orfeo ed Euridice", "Christoph Willibald Gluck"): {(None, 1762, None)},
    ("Le nozze di Figaro", "Wolfgang Amadeus Mozart"): {(None, 1786, None)},
    ("Das verratene Meer", "Hans Werner Henze"): {(None, 1990, 2005)},
    ("Otello", "Giuseppe Verdi"): {(None, 1887, None)},
    ("Rappresentatione di Anima et di Corpo", "Emilio de' Cavalieri"): {
        (None, 1600, None)
    },
    ("La concordia de' pianeti", "Antonio Caldara"): {(None, 1723, None)},
    ("La traviata", "Giuseppe Verdi"): {(None, 1853, None)},
    ("Die Zauberflöte", "Wolfgang Amadeus Mozart"): {(None, 1791, None)},
    ("Intolleranza 1960", "Luigi Nono"): {(None, 1961, None)},
    ("Armida", "Antonio Salieri"): {(None, 1771, None)},
    ("Cajo Fabricio", "Johann Adolph Hasse"): {(None, 1731, None)},
    ("Lohengrin", "Richard Wagner"): {(None, 1850, None)},
    ("Leyla und Medjnun", "Detlev Glanert"): {(None, 1988, 2017)},
    ("Macbeth", "Giuseppe Verdi"): {(None, 1847, 1865)},
    ("I Capuleti e i Montecchi", "Vincenzo Bellini"): {(None, 1830, None)},
    ("L’incoronazione di Poppea", "Claudio Monteverdi"): {(None, 1643, None)},
    ("Carmen", "Georges Bizet"): {(None, 1875, None)},
    ("Alcina", "Georg Friedrich Händel"): {(None, 1735, None)},
    ("Il trionfo del Tempo e del Disinganno", "Georg Friedrich Händel"): {
        (None, 1707, None)
    },
    ("Tosca", "Giacomo Puccini"): {(None, 1900, None)},
    ("Le roi Carotte", "Jacques Offenbach"): {(None, 1872, None)},
    ("Don Pasquale", "Gaetano Donizetti"): {(None, 1843, None)},
    ("Die Entführung aus dem Serail", "Wolfgang Amadeus Mozart"): {(None, 1782, None)},
    ("Porgy and Bess", "George Gershwin"): {(None, 1935, None)},
    ("Osud", "Leoš Janáček"): {(None, 1907, 1958)},
    ("Don Carlos", "Giuseppe Verdi"): {(None, 1867, None)},
    ("La Fille du régiment", "Gaetano Donizetti"): {(None, 1840, None)},
    ("Carlo il Calvo", "Nicola Antonio Porpora"): {(None, 1738, None)},
    ("Zazà", "Ruggero Leoncavallo"): {(None, 1900, None)},
    ("Toteis", "Manuela Kerer"): {(None, 2020, None)},
    ("L’elisir d’amore", "Gaetano Donizetti"): {(None, 1832, None)},
    ("Madama Butterfly", "Giacomo Puccini"): {(None, 1904, None)},
    ("L’empio punito", "Alessandro Melani"): {(None, 1669, None)},
    ("Così fan tutte", "Wolfgang Amadeus Mozart"): {(None, 1790, None)},
    ("Königskinder", "Engelbert Humperdinck"): {(None, 1910, None)},
    ("Solomon", "Georg Friedrich Händel"): {(None, 1749, None)},
    ("Der Schmied von Gent", "Franz Schreker"): {(None, 1932, None)},
    ("La dame blanche", "François-Adrien Boieldieu"): {(None, 1825, None)},
    ("Fidelio", "Ludwig van Beethoven"): {(1805, 1806, 1814)},
    ("Serse", "Georg Friedrich Händel"): {(None, 1738, None)},
    ("Tolomeo", "Georg Friedrich Händel"): {(None, 1728, None)},
    ("Isis", "Jean-Baptiste Lully"): {(None, 1677, None)},
    ("Egmont", "Christian Jost"): {(None, 2020, None)},
    ("Written on skin", "George Benjamin"): {(None, 2012, None)},
    ("Rusalka", "Antonín Dvořák"): {(None, 1901, None)},
    ("Irene", "Johann Adolph Hasse"): {(None, 1738, None)},
    ("Las fortunas de Andrómeda y Perseo", "Juan Hidalgo"): {(None, 1653, None)},
    ("Les Boréades", "Jean-Philippe Rameau"): {(None, 1763, None)},
    ("Radamisto", "Georg Friedrich Händel"): {(None, 1720, None)},
    ("Pénélope", "Gabriel Fauré"): {(None, 1913, None)},
    ("Halka", "Stanisław Moniuszko"): {(None, 1858, None)},
    ("Giustino", "Georg Friedrich Händel"): {(None, 1737, None)},
    ("Orlando", "Olga Neuwirth"): {(None, 2019, None)},
    ("Iris", "Pietro Mascagni"): {(None, 1898, None)},
    ("Šelma sedlák", "Antonín Dvořák"): {(None, 1877, None)},
    ("La vestale", "Gaspare Spontini"): {(None, 1807, None)},
    ("Semele", "Johann Adolph Hasse"): {(None, 1726, None)},
    ("Ercole amante", "Francesco Cavalli"): {(None, 1662, None)},
    ("La finta giardiniera", "Wolfgang Amadeus Mozart"): {(None, 1775, None)},
    ("Libuše", "Bedřich Smetana"): {(None, 1872, 1881)},
    ("Der Reigen", "Bernhard Lang"): {(None, 2014, None)},
    ("Lady Macbeth von Mzensk", "Dmitri Schostakowitsch"): {(None, 1934, None)},
    ("Tamerlano", "Georg Friedrich Händel"): {(None, 1724, None)},
    ("The Bassarids", "Hans Werner Henze"): {(None, 1966, None)},
    ("La clemenza di Tito", "Wolfgang Amadeus Mozart"): {(None, 1791, None)},
    ("Merope", "Riccardo Broschi"): {(None, 1732, None)},
    ("Jakobín", "Antonín Dvořák"): {(None, 1889, None)},
    ("Le prophète", "Giacomo Meyerbeer"): {(None, 1849, None)},
    ("A midsummer night’s dream", "Benjamin Britten"): {(None, 1960, None)},
    ("The Rape of Lucretia", "Benjamin Britten"): {(None, 1946, None)},
    ("Angels in America", "Péter Eötvös"): {(None, 2004, None)},
    ("La Bohème", "Giacomo Puccini"): {(None, 1896, None)},
    ("Otello", "Gioachino Rossini"): {(None, 1816, None)},
    ("Les contes d'Hoffmann", "Jacques Offenbach"): {(None, 1881, None)},
    ("Tristan und Isolde", "Richard Wagner"): {(None, 1865, None)},
    ("Die Meistersinger von Nürnberg", "Richard Wagner"): {(None, 1868, None)},
    ("La Dori", "Antonio Cesti"): {(None, 1657, None)},
    ("Œdipe", "George Enescu"): {(None, 1936, None)},
    ("Agrippina", "Georg Friedrich Händel"): {(None, 1709, None)},
    ("Matilde di Shabran", "Gioachino Rossini"): {(None, 1821, None)},
    ("I tre gobbi", "Manuel Garcia"): {(None, 1831, None)},
    ("Romilda e Costanza", "Giacomo Meyerbeer"): {(None, 1817, None)},
    ("Arianna a Naxos", "Joseph Haydn"): {(None, 1789, None)},
    ("Il buon marito", "Georg Anton Benda"): {(None, 1766, None)},
    ("Dafne in lauro", "Johann Joseph Fux"): {(None, 1714, None)},
    ("Aida", "Giuseppe Verdi"): {(None, 1871, None)},
    ("La morte d’Abel", "Antonio Caldara"): {(None, 1732, None)},
    ("Polifemo", "Nicola Antonio Porpora"): {(None, 1735, None)},
    ("Don Quichotte", "Jules Massenet"): {(None, 1910, None)},
    ("Rodelinda", "Georg Friedrich Händel"): {(None, 1725, None)},
    ("Dantons Tod", "Gottfried von Einem"): {(None, 1947, None)},
    ("Oberon, König der Elfen", "Carl Maria von Weber"): {(None, 1826, None)},
    ("Médée", "Luigi Cherubini"): {(None, 1797, None)},
    ("Candide", "Leonard Bernstein"): {(None, 1974, None)},
    ("Les contes d’Hoffmann", "Jacques Offenbach"): {(None, 1881, None)},
    ("Król Roger", "Karol Szymanowski"): {(None, 1926, None)},
    ("Fierabras", "Franz Schubert"): {(None, 1823, 1897)},
    ("Poro", "Georg Friedrich Händel"): {(None, 1731, None)},
    ("Orlando", "Georg Friedrich Händel"): {(None, 1733, None)},
    ("Powder Her Face", "Thomas Adès"): {(None, 1995, None)},
    ("Orest", "Manfred Trojahn"): {(None, 2011, None)},
    ("Dido and Aeneas", "Henry Purcell"): {(None, 1689, None)},
    ("The epic of Gilgamesh", "Bohuslav Martinů"): {(None, 1955, 1958)},
    ("Der fliegende Holländer", "Richard Wagner"): {(None, 1841, 1843)},
    ("Orlando furioso", "Antonio Vivaldi"): {(None, 1727, None)},
    ("Der Freischütz", "Carl Maria von Weber"): {(None, 1821, None)},
    ("Penthesilea", "Othmar Schoeck"): {(None, 1927, None)},
    ("Lotario", "Georg Friedrich Händel"): {(None, 1729, None)},
    ("L’enfant et les sortilèges", "Maurice Ravel"): {(None, 1925, None)},
    ("The trial", "Philip Glass"): {(None, 2014, None)},
    ("Dalibor", "Bedřich Smetana"): {(None, 1868, 1870)},
    ("Undine", "Pjotr Iljitsch Tschaikowski"): {(None, 1869, None)},
    ("Mazeppa", "Pjotr Iljitsch Tschaikowski"): {(None, 1884, None)},
    ("Elias", "Mendelssohn Bartholdy"): {(None, 1846, None)},
    ("Karl V.", "Ernst Krenek"): {(None, 1938, None)},
    ("Lucia di Lammermoor", "Gaetano Donizetti"): {(None, 1835, None)},
    ("Jonny spielt auf", "Ernst Krenek"): {(None, 1927, None)},
    ("King Arthur", "Henry Purcell"): {(None, 1691, None)},
    ("Peter Schmoll", "Carl Maria von Weber"): {(None, 1802, None)},
    ("Götterdämmerung", "Richard Wagner"): {(None, 1876, None)},
    ("Manon", "Jules Massenet"): {(None, 1884, None)},
    ("Euryanthe", "Carl Maria von Weber"): {(None, 1823, None)},
    ("Messiah", "Georg Friedrich Händel"): {(None, 1741, None)},
    ("Die Weiden", "Johannes Maria Staud"): {(None, 2018, None)},
    ("Hippolyte et Aricie", "Jean-Philippe Rameau"): {(1733, 1757, 1767)},
    ("Les contes d’ Hoffmann", "Jacques Offenbach"): {(None, 1881, None)},
    ("Tarare", "Antonio Salieri"): {(None, 1787, None)},
    ("Teseo", "Georg Friedrich Händel"): {(None, 1713, None)},
    ("Šárka", "Leoš Janáček"): {(1887, 1925, 2018)},
    ("I masnadieri", "Giuseppe Verdi"): {(None, 1847, None)},
    ("Il tabarro", "Giacomo Puccini"): {(None, 1918, None)},
    ("Weiße Rose", "Udo Zimmermann"): {(None, 1986, None)},
    ("Jenůfa", "Leoš Janáček"): {(None, 1904, None)},
    ("The Beggar’s Opera", "Johann Christoph Pepusch"): {(None, 1728, None)},
    ("Guillaume Tell", "Gioachino Rossini"): {(None, 1829, 1831)},
    ("Les Troyens", "Hector Berlioz"): {(None, 1858, 1890)},
    ("Zar und Zimmermann", "Albert Lortzing"): {(None, 1837, None)},
    ("Die Zauberinsel", "Henry Purcell"): {(None, 2018, None)},
    ("Die tote Stadt", "Erich Wolfgang Korngold"): {(None, 1920, None)},
    ("Die Liebe zu den drei Orangen", "Sergei Prokofjew"): {(None, 1921, None)},
    ("Medée", "Luigi Cherubini"): {(None, 1797, None)},
    ("Gismondo, rè di Polonia", "Leonardo Vinci"): {(None, 1727, None)},
    ("Jeanne & Gilles", "François-Pierre Descamps"): {(None, 2018, None)},
    ("Julie & Jean", "Gerhard Schedl"): {(None, 2003, None)},
    ("L’italiana in Algeri", "Gioachino Rossini"): {(None, 1813, None)},
    ("Beatrice Cenci", "Berthold Goldschmidt"): {(1950, 88, 94)},
    ("Orlando Paladino", "Joseph Haydn"): {(None, 1782, None)},
    ("Die Gezeichneten", "Franz Schreker"): {(None, 1918, None)},
    ("Semele", "Georg Friedrich Händel"): {(None, 1744, None)},
    ("Ti vedo, ti sento, mi perdo", "Salvatore Sciarrino"): {(None, 2017, None)},
    ("Die Nase", "Dmitri Schostakowitsch"): {(None, 1930, None)},
    ("Il viaggio a Reims", "Gioachino Rossini"): {(None, 1825, None)},
    ("La Gioconda", "Amilcare Ponchielli"): {(None, 1876, None)},
    ("Radames", "Péter Eötvös"): {(None, 1976, None)},
    ("Death in Venice", "Benjamin Britten"): {(None, 1973, None)},
    ("Parnasso in festa", "Georg Friedrich Händel"): {(None, 1734, None)},
    ("Ormisda", "Georg Friedrich Händel"): {(None, 1730, None)},
    ("Berenice", "Georg Friedrich Händel"): {(None, 1737, None)},
    ("Samson et Dalila", "Camille Saint-Saëns"): {(None, 1877, None)},
    ("Simon Boccanegra", "Giuseppe Verdi"): {(None, 1857, 1881)},
    ("Andrea Chénier", "Umberto Giordano"): {(None, 1896, None)},
    ("Die Walküre", "Richard Wagner"): {(None, 1870, None)},
    ("Marilyn Forever", "Gavin Bryars"): {(None, 2013, None)},
    ("Siegfried", "Richard Wagner"): {(None, 1876, None)},
    ("Das Wunder der Heliane", "Erich Wolfgang Korngold"): {(None, 1921, None)},
    ("Das Rheingold", "Richard Wagner"): {(None, 1869, None)},
    ("Vasco da Gama (L’Africaine)", "Giacomo Meyerbeer"): {(None, 1865, 2013)},
    ("Die Schuldigkeit des ersten Gebots", "Wolfgang Amadeus Mozart"): {
        (None, 1767, None)
    },
    ("Der Besuch der alten Dame", "Gottfried von Einem"): {(None, 1971, None)},
    ("L’isola disabitata", "Joseph Haydn"): {(None, 1779, None)},
    ("A quiet place", "Leonard Bernstein"): {(None, 1984, 2013)},
    ("Ariane et Barbe-Bleue", "Paul Dukas"): {(None, 1907, None)},
    ("Ariodante", "Georg Friedrich Händel"): {(None, 1735, None)},
    ("Die Rheinnixen", "Jacques Offenbach"): {(None, 1864, None)},
    ("Il serpente di bronzo", "Jan Dismas Zelenka"): {(None, 1730, None)},
    ("Hercules", "Georg Friedrich Händel"): {(None, 1745, None)},
    ("Ernani", "Giuseppe Verdi"): {(None, 1844, None)},
    ("Saul", "Georg Friedrich Händel"): {(None, 1739, None)},
    ("Pelléas et Mélisande", "Claude Debussy"): {(None, 1902, None)},
    ("Armida", "Joseph Haydn"): {(None, 1784, None)},
    ("Pigmalion", "Jean-Philippe Rameau"): {(None, 1748, None)},
    ("La damnation de Faust", "Hector Berlioz"): {(None, 1846, None)},
    ("Sadko", "Nikolai Rimski-Korsakow"): {(None, 1897, None)},
    ("Giulietta e Romeo", "Niccolò Antonio Zingarelli"): {(None, 1796, None)},
    ("Publio Cornelio Scipione", "Georg Friedrich Händel"): {(None, 1726, None)},
    ("Maria Stuarda", "Gaetano Donizetti"): {(None, 1834, 1835)},
    ("L’Europe galante", "André Campra"): {(None, 1697, None)},
    ("I puritani", "Vincenzo Bellini"): {(None, 1835, None)},
    ("The Mikado", "Arthur Sullivan"): {(None, 1885, None)},
    ("Siegfried (Ring-Trilogie)", "Richard Wagner"): {(None, 1876, None)},
    ("Lulu", "Alban Berg"): {(None, 1937, None)},
    ("Le Prophète", "Giacomo Meyerbeer"): {(None, 1849, None)},
    ("Tannhäuser und der Sängerkrieg auf Wartburg", "Richard Wagner"): {
        (None, 1845, None)
    },
    ("I Lombardi alla prima crociata", "Giuseppe Verdi"): {(None, 1843, None)},
    ("Die Antilope", "Johannes Maria Staud"): {(None, 2014, None)},
    ("Hamlet", "Ambroise Thomas"): {(None, 1868, None)},
    ("Wozzeck", "Alban Berg"): {(None, 1925, None)},
    ("Die Kluge", "Carl Orff"): {(None, 1943, None)},
    ("Der Mond", "Carl Orff"): {(None, 1939, None)},
    ("Rigoletto", "Giuseppe Verdi"): {(None, 1851, None)},
    ("María de Buenos Aires", "Astor Piazzolla"): {(None, 1968, None)},
    ("Mateo", "Martin Palmeri"): {(None, 1999, None)},
    ("Arianna in Nasso", "Nicola Antonio Porpora"): {(None, 1733, None)},
    ("Ottone", "Georg Friedrich Händel"): {(None, 1723, None)},
    ("Chowanschtschina", "Modest Mussorgski"): {(None, 1880, 1960)},
    ("La Rosinda", "Francesco Cavalli"): {(None, 1651, None)},
    ("Il trovatore", "Giuseppe Verdi"): {(None, 1853, None)},
    ("Mosé in Egitto", "Gioachino Rossini"): {(None, 1818, None)},
    ("Zoroastre", "Jean-Philippe Rameau"): {(None, 1749, 1756)},
    ("Le comte Ory", "Gioachino Rossini"): {(None, 1828, None)},
    ("Idoménéé", "André Campra"): {(None, 1712, None)},
    ("Norma", "Vincenzo Bellini"): {(None, 1831, None)},
    ("Mondparsifal Alpha 1-8 (Erzmutterz der Abwehr)", "Bernhard Lang"): {
        (None, 2017, None)
    },
    ("La donna del lago", "Gioachino Rossini"): {(None, 1819, None)},
    ("La scuola de’ gelosi", "Antonio Salieri"): {(None, 1778, 1783)},
    ("Leonce und Lena", "Erich Zeisl"): {(None, 1938, 1952)},
    ("Das geheime Königreich", "Ernst Krenek"): {(None, 1928, None)},
    ("Schwergewicht oder Die Ehre der Nation", "Ernst Krenek"): {(None, 1928, None)},
    ("Der Diktator", "Ernst Krenek"): {(None, 1928, None)},
    ("Siroe", "Johann Adolph Hasse"): {(None, 1763, None)},
    ("La liberazione di Ruggiero dall’isola d’Alcina", "Francesca Caccini"): {
        (None, 1625, None)
    },
    ("Die Schöpfung", "Joseph Haydn"): {(None, 1798, None)},
    ("Elegie für junge Liebende", "Hans Werner Henze"): {(None, 1961, None)},
    ("La Rondine", "Giacomo Puccini"): {(None, 1917, None)},
    ("Die Harmonie der Welt", "Paul Hindemith"): {(None, 1957, None)},
    ("La Juive", "Jacques Fromental Halévy"): {(None, 1835, None)},
    ("Medea", "Aribert Reimann"): {(None, 2010, None)},
    ("Parsifal", "Richard Wagner"): {(None, 1882, None)},
    ("Il prigioniero", "Luigi Dallapiccola"): {(None, 1949, None)},
    ("Der Zwerg", "Alexander von Zemlinsky"): {(None, 1922, None)},
    ("Germanico in Germania", "Nicola Antonio Porpora"): {(None, 1732, None)},
    ("Elisabetta, Regina d’Inghilterra", "Gioachino Rossini"): {(None, 1815, None)},
    ("Arsilda", "Antonio Vivaldi"): {(None, 1716, None)},
    ("Oreste", "Georg Friedrich Händel"): {(None, 1734, None)},
    ("Il mondo della luna", "Joseph Haydn"): {(None, 1777, None)},
    ("Suor Angelica", "Giacomo Puccini"): {(None, 1918, None)},
    ("Piramo e Tisbe", "Johann Adolph Hasse"): {(None, 1768, None)},
    ("Peer Gynt", "Werner Egk"): {(None, 1938, None)},
    ("Der feurige Engel", "Sergei Prokofjew"): {(None, 1927, 1954)},
    ("Semiramide", "Gioachino Rossini"): {(None, 1823, None)},
    ("Limonen aus Sizilien", "Manfred Trojahn"): {(None, 2003, None)},
    ("Der Kaiser von Atlantis oder die Tod-Verweigerung", "Viktor Ullmann"): {
        (None, 1943, None)
    },
    ("Lucio Cornelio Silla", "Georg Friedrich Händel"): {(None, 1713, None)},
    ("Juditha triumphans devicta Holofernis barbarie", "Antonio Vivaldi"): {
        (None, 1716, None)
    },
    ("The Fairy Queen", "Henry Purcell"): {(None, 1692, None)},
    ("Roméo et Juliette", "Charles Gounod"): {(None, 1867, None)},
    ("La sonnambula", "Vincenzo Bellini"): {(None, 1831, None)},
    ("Adriano in Siria", "Giovanni Battista Pergolesi"): {(None, 1734, None)},
    ("Ezio", "Christoph Willibald Gluck"): {(None, 1750, None)},
    ("Falstaff", "Giuseppe Verdi"): {(None, 1893, None)},
    ("La fanciulla del West", "Giacomo Puccini"): {(None, 1910, None)},
    ("Hybris", "Šimon Voseček"): {(None, 2016, None)},
    ("Soma", "Christof Dienz"): {(None, 2016, None)},
    ("Nemesis", "Hannes Löschel"): {(None, 2016, None)},
    ("La cenerentola", "Gioachino Rossini"): {(None, 1817, None)},
    ("Pallas Athene weint", "Ernst Krenek"): {(None, 1955, None)},
    ("Armide", "Christoph Willibald Gluck"): {(None, 1777, None)},
    ("Falstaff ossia Le tre burle", "Antonio Salieri"): {(None, 1799, None)},
    ("Les Horaces", "Antonio Salieri"): {(None, 1786, None)},
    ("La traviata remixed", "Giuseppe Verdi"): {(None, 1853, None)},
    ("Les Indes Galantes", "Jean-Philippe Rameau"): {(None, 1735, None)},
    ("Mefistofele", "Arrigo Boito"): {(None, 1868, 1875)},
    ("Iphigénie en Tauride", "Niccolò Piccini"): {(None, 1781, None)},
    ("Cavalleria rusticana", "Pietro Mascagni"): {(None, 1890, None)},
    ("Pagliacci", "Ruggero Leoncavallo"): {(None, 1892, None)},
    ("Manon Lescaut", "Giacomo Puccini"): {(None, 1893, None)},
    ("Alceste", "Christoph Willibald Gluck"): {(None, 1767, 78)},
    ("Acis and Galatea", "Georg Friedrich Händel"): {(None, 1718, None)},
    ("Sosarme, Re di Media", "Georg Friedrich Händel"): {(None, 1732, None)},
    ("Hänsel und Gretel", "Engelbert Humperdinck"): {(None, 1893, None)},
    ("Die Passagierin", "Mieczysław Weinberg"): {(None, 1968, None)},
    ("Boris Godunow", "Modest Mussorgski"): {(None, 1874, None)},
    ("Il turco in Italia", "Gioachino Rossini"): {(None, 1814, None)},
    ("Veremonda, l’amazzone di Aragona", "Francesco Cavalli"): {(None, 1652, None)},
    ("Turandot", "Giacomo Puccini"): {(None, 1924, None)},
    ("Lucio Silla", "Wolfgang Amadeus Mozart"): {(None, 1772, None)},
    ("Un ballo in maschera", "Giuseppe Verdi"): {(None, 1859, None)},
    ("Arminio", "Georg Friedrich Händel"): {(None, 1737, None)},
    ("The Greek Passion", "Bohuslav Martinů"): {(None, 1959, 1999)},
    ("Der Vampyr", "Heinrich Marschner"): {(None, 1828, None)},
    ("Tri Sestri", "Péter Eötvös"): {(None, 1998, None)},
    ("Rienzi, der letzte der Tribunen", "Richard Wagner"): {(None, 1842, None)},
    ("The turn of the screw", "Benjamin Britten"): {(None, 1954, None)},
    ("Nabucco", "Giuseppe Verdi"): {(None, 1842, None)},
    ("Idomeneo", "Wolfgang Amadeus Mozart"): {(None, 1781, None)},
    ("Luisa Miller", "Giuseppe Verdi"): {(None, 1849, None)},
    ("Armide", "Jean-Baptiste Lully"): {(None, 1686, None)},
    ("Antigone", "Tommaso Traetta"): {(None, 1772, None)},
    ("Vec Makropulos", "Leoš Janáček"): {(None, 1926, None)},
    ("La gazza ladra", "Gioachino Rossini"): {(None, 1817, None)},
    ("Don Chisciotte in Sierra Morena", "Francesco Bartolomeo Conti"): {
        (None, 1719, None)
    },
    ("Xerse", "Francesco Cavalli"): {(None, 1654, 1660)},
    ("Der ferne Klang", "Franz Schreker"): {(None, 1912, None)},
    ("Catone in Utica", "Leonardo Vinci"): {(None, 1728, None)},
    ("Hans Heiling", "Heinrich Marschner"): {(None, 1833, None)},
    ("Das Tagebuch der Anne Frank", "Grigori Frid"): {(None, 1969, None)},
    ("Lo speziale", "Joseph Haydn"): {(None, 1768, None)},
    ("Cardillac", "Paul Hindemith"): {(None, 1926, None)},
    ("The Tempest", "Thomas Adès"): {(None, 2004, None)},
    ("Les mamelles de Tirésias", "Francis Poulenc"): {(None, 1947, None)},
    ("L’ heure espagnole", "Maurice Ravel"): {(None, 1911, None)},
    ("Jephtha", "Georg Friedrich Händel"): {(None, 1752, None)},
    ("Luci mie traditrici", "Salvatore Sciarrino"): {(None, 1998, None)},
    ("La clemenza di Tito", "Christoph Willibald Gluck"): {(None, 1752, None)},
    ("La mère coupable", "Darius Milhaud"): {(None, 1966, None)},
    ("Erwartung", "Arnold Schoenberg"): {(None, 1924, None)},
    ("Zaïs", "Jean-Philippe Rameau"): {(None, 1748, None)},
    ("La vie parisienne", "Jacques Offenbach"): {(None, 1866, None)},
    ("Gli Uccellatori", "Florian Leopold Gassmann"): {(None, 1759, 1768)},
    ("Geschichten aus dem Wiener Wald", "Heinz Karl Gruber"): {(None, 2014, None)},
    ("Albert Herring", "Benjamin Britten"): {(None, 1947, None)},
    ("Werther", "Jules Massenet"): {(None, 1892, None)},
    ("Il barbiere di Siviglia", "Giovanni Paisiello"): {(None, 1782, None)},
    ("Cinq-Mars", "Charles Gounod"): {(None, 1877, None)},
    ("La Straniera", "Vincenzo Bellini"): {(None, 1829, None)},
    ("Le convenienze ed inconvenienze teatrali", "Gaetano Donizetti"): {
        (None, 1830, None)
    },
    ("The Blind", "Lera Auerbach"): {(None, 2011, None)},
    ("Pique Dame", "Pjotr Iljitsch Tschaikowski"): {(None, 1890, None)},
    ("American Lulu", "Olga Neuwirth"): {(None, 2011, None)},
    ("Rinaldo", "Georg Friedrich Händel"): {(None, 1711, None)},
    ("Les pêcheurs de perles", "Georges Bizet"): {(None, 1863, None)},
    ("Demofoonte", "Christoph Willibald Gluck"): {(None, 1743, None)},
    ("Iphigénie en Aulide et Tauride", "Christoph Willibald Gluck"): {
        (None, 1774, None)
    },
    ("La Stellidaura vendicante", "Francesco Provenzale"): {(None, 1674, None)},
    ("Roberto Devereux", "Gaetano Donizetti"): {(None, 1837, None)},
    ("Onkel Präsident", "Friedrich Cerha"): {(None, 2013, None)},
    ("Charodeyka", "Pjotr Iljitsch Tschaikowski"): {(None, 1887, None)},
    ("Punch and Judy", "Harrison Birtwistle"): {(None, 1968, None)},
    ("Billy Budd", "Benjamin Britten"): {(None, 1951, None)},
    ("Castor et Pollux", "Jean-Philippe Rameau"): {(None, 1737, 1754)},
    ("L’Olimpiade", "Josef Mysliveček"): {(None, 1778, None)},
    ("Platée", "Jean-Philippe Rameau"): {(None, 1745, None)},
    ("Admeto, Re di Tessaglia", "Georg Friedrich Händel"): {(None, 1727, None)},
    ("Mare Nostrum", "Mauricio Kagel"): {(None, 1975, None)},
    ("An Index of Metals", "Fausto Romitelli"): {(None, 2003, None)},
    ("I due Foscari", "Giuseppe Verdi"): {(None, 1844, None)},
    ("Adriano in Siria", "Francesco Maria Veracini"): {(None, 1735, None)},
    ("Lazarus", "Franz Schubert / Charles Ives"): {(None, 1820, 1863)},
    ("La Cenerentola", "Gioachino Rossini"): {(None, 1817, None)},
    ("Les Danaïdes", "Antonio Salieri"): {(None, 1784, None)},
    ("Anna Bolena", "Gaetano Donizetti"): {(None, 1830, None)},
    ("A Harlot’s Progress", "Iain Bell"): {(None, 2013, None)},
    ("Aci, Galatea e Polifemo", "Georg Friedrich Händel"): {(None, 1708, None)},
    ("What Price Confidence", "Ernst Krenek"): {(None, 1945, None)},
    ("The Rake’s Progress", "Igor Strawinski"): {(None, 1951, None)},
    ("Alessandro", "Georg Friedrich Händel"): {(None, 1726, None)},
    ("Attila", "Giuseppe Verdi"): {(None, 1846, None)},
    ("Das Wundertheater", "Hans Werner Henze"): {(None, 1965, None)},
    ("Le vaisseau fantôme", "Pierre-Louis Dietsch"): {(None, 1842, None)},
    ("Amadigi di Gaula", "Georg Friedrich Händel"): {(None, 1715, None)},
    ("Béatrice et Bénédict", "Hector Berlioz"): {(None, 1862, None)},
    ("Arianna in Creta", "Georg Friedrich Händel"): {(None, 1734, None)},
    ("Le nozze di Teti, e di Peleo", "Gioachino Rossini"): {(None, 1816, None)},
    ("La scala di seta", "Gioachino Rossini"): {(None, 1812, None)},
    ("I Vespri Siciliani", "Giuseppe Verdi"): {(None, 1855, None)},
    ("La Sonnambula", "Vincenzo Bellini"): {(None, 1831, None)},
    ("Aufstieg und Fall der Stadt Mahagonny", "Kurt Weill"): {(None, 1930, None)},
    ("Die lustige Witwe", "Franz Lehár"): {(None, 1905, None)},
    ("Il trionfo di Clelia", "Christoph Willibald Gluck"): {(None, 1763, None)},
    ("Atys", "Jean-Baptiste Lully"): {(None, 1676, None)},
    ("Thaïs", "Jules Massenet"): {(None, 1894, None)},
    ("Beatrice di Tenda", "Vincenzo Bellini"): {(None, 1833, None)},
    ("Caino overo il primo omicidio", "Alessandro Scarlatti"): {(None, 1707, None)},
    ("San Giovanni Battista", "Alessandro Stradella"): {(None, 1675, None)},
    ("Fürst Igor", "Alexander Borodin"): {(None, 1890, None)},
    ("Bajazet", "Antonio Vivaldi"): {(None, 1735, None)},
    ("Die Teufelskäthe (Čert a Káča)", "Antonín Dvořák"): {(None, 1899, None)},
    ("Die verkaufte Braut", "Bedřich Smetana"): {(None, 1866, None)},
    ("Julietta (Snář)", "Bohuslav Martinů"): {(None, 1938, None)},
    ("Marienspiele (Hry o Marii)", "Bohuslav Martinů"): {(None, 1934, None)},
    ("Herzog Blaubarts Burg", "Béla Bartók"): {(None, 1918, None)},
    ("Il ritorno l’Ulisse in patria", "Claudio Monteverdi"): {(None, 1640, None)},
    ("L’Orfeo", "Claudio Monteverdi"): {(None, 1607, None)},
    ("Der Operndirektor", "Domenico Cimarosa"): {(None, 1786, None)},
    ("Katrena (Krútňava)", "Eugen Suchoň"): {(None, 1949, None)},
    ("Le Malentendu", "Fabián Pasinello"): {(None, 2016, None)},
    ("Rodrigo", "Georg Friedrich Händel"): {(None, 1707, None)},
    ("Der Ficus spricht", "Gerhard Schedl"): {(None, 1998, None)},
    ("La Didone", "Francesco Cavalli"): {(None, 1641, None)},
    ("Les Huguenots", "Giacomo Mayerbeer"): {(None, 1836, None)},
    ("Gianni Schicchi", "Giacomo Puccini"): {(None, 1918, None)},
    ("La gazzetta", "Gioachino Rossini"): {(None, 1816, None)},
    ("Oedipus Rex", "Igor Strawinsky"): {(None, 1927, None)},
    ("Olympia", "Jacques Offenbach"): {(None, 1894, None)},
    ("The King Arthur Séance: On Henry Purcell’s Shoulders", "Helmut Jasbar"): {
        (None, 2014, None)
    },
    ("Die Fledermaus", "Johann Strauss"): {(None, 1874, None)},
    ("Semiramide", "Leonardo Vinci / Georg Friedrich Händel"): {(None, 1733, None)},
    ("Anfang eines Romans (Počátek románu)", "Leoš Janáček"): {(None, 1894, None)},
    ("Die Ausflüge des Herrn Brouček (Výlety páně Broučkovy)", "Leoš Janáček"): {
        (None, 1921, None)
    },
    ("Das schlaue Füchslein", "Leoš Janáček"): {(None, 1924, None)},
    ("Kátja Kabanová", "Leoš Janáček"): {(None, 1921, None)},
    ("Aus einem Totenhaus (Z mrtvého domu)", "Leoš Janáček"): {(None, 1930, None)},
    ("Der Jahrmarkt von Sorotschinzi", "Modest Mussorgski"): {(None, 1880, 1932)},
    ("Der goldene Hahn (Solotoi petbuschok)", "Nikolai Rimski-Korsakow"): {
        (None, 1909, None)
    },
    ("Die Zarenbraut (Zarskaja newesta)", "Nikolai Rimski-Korsakow"): {
        (None, 1899, None)
    },
    ("Die lustigen Weiber von Windsor", "Otto Nicolai"): {(None, 1849, None)},
    ("Die Jungfrau von Orleans", "Pjotr Iljitsch Tschaikowski"): {(None, 1881, None)},
    ("Feuersnot", "Richard Strauss"): {(None, 1901, None)},
    ("Salome", "Richard Strauss"): {(None, 1905, None)},
    ("Elektra", "Richard Strauss"): {(None, 1909, None)},
    ("Der Rosenkavalier", "Richard Strauss"): {(None, 1911, None)},
    ("Ariadne auf Naxos", "Richard Strauss"): {(None, 1916, None)},
    ("Die Frau ohne Schatten", "Richard Strauss"): {(None, 1919, None)},
    ("Die ägyptische Helena", "Richard Strauss"): {(None, 1928, None)},
    ("Arabella", "Richard Strauss"): {(None, 1933, None)},
    ("Die schweigsame Frau", "Richard Strauss"): {(None, 1935, None)},
    ("Daphne", "Richard Strauss"): {(None, 1938, None)},
    ("Die Liebe der Danae", "Richard Strauss"): {(None, 1952, None)},
    ("Capriccio", "Richard Strauss"): {(None, 1942, None)},
    (
        "La terribile e spaventosa storia del principe di Venosa e della bella Maria",
        "Salvatore Sciarrino",
    ): {(None, 1999, None)},
    ("Die Spinnstube (Székely fonó)", "Zoltán Kodály"): {(None, 1932, None)},
    ("Der Spieler", "Sergei Prokofjew"): {(None, 1929, None)},
    ("Η Χαλιμά", "Θεόφραστος Σακελλαρίδης"): {(None, 1926, None)},
    ("Θέλω να δω τον Πάπα", "Θεόφραστος Σακελλαρίδης"): {(None, 1920, None)},
    ("Ο Βαφτιστικός", "Θεόφραστος Σακελλαρίδης"): {(None, 1918, None)},
    ("Η Κρητικοπούλα", "Σπύρος Σαμάρας"): {(None, 1916, None)},
}
